import {RF} from '@theme';

export const Typography = {
  FONTS: {
    SIZE: {
      LARGEST: RF(40),
      LARGER: RF(38),
      XXXLARGE: RF(36),
      XXLARGE: RF(32),
      XLARGE: RF(24),
      LARGE: RF(20),
      MEDIUM: RF(18),
      SMALL: RF(16),
      XSMALL: RF(14),
      XXSMALL: RF(12),
      XXXSMALL: RF(10),
      XXXXSMALL: RF(8),
    },
    TYPE: {
      LIGHT: 'Lato-Light',
      REGULAR: 'PlusJakartaSans-Regular',
      MEDIUM: 'PlusJakartaSans-Medium',
      SEMIBOLD: 'PlusJakartaSans-SemiBold',
      BOLD: 'PlusJakartaSans-Bold',
      BOLDER: 'PlusJakartaSans-ExtraBold',
      BOLDEST: 'PlusJakartaSans-ExtraBoldItalic',
      mulish_regular: 'Mulish-Regular',
      mulish_bold: 'Mulish-Bold',
      mulish_medium: 'Mulish-Medium',
    },
  },
  MARGIN: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    MID_LOW: RF(12),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
    NOVAHIGH: RF(60),
  },
  PADDING: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
  },
  RADIUS: {
    BOX: RF(10),
    SMALLBOX: RF(5),
    OVAL: RF(24),
    medium: RF(30),
    FULL: RF(100),
  },
};
